# Cask tap
tap 'teamookla/speedtest'

# Zsh
brew 'zsh'
brew 'zsh-autocomplete'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'bat'
brew 'fzf'
brew 'fd'
brew 'zoxide'
brew 'delta'
brew 'powerlevel10k'
brew 'pygments'

# Tmux
brew 'tmux'
brew 'tmuxp'

# Tools
brew 'coreutils'
brew 'git'
brew 'pandoc'
brew 'tree'
brew 'pdfgrep'
brew 'eza'
brew 'ncdu'

# Development
brew 'emacs'
brew 'rbenv'
brew 'pyenv'
brew 'ruby-build'
cask 'visual-studio-code'

# Work + Sync
cask 'zoom'
cask 'google-drive'

# Menubar
cask 'mac2imgur'
cask '1password'
cask 'itsycal'
cask 'tiles'
cask 'displaperture'
cask 'hiddenbar'
cask 'xbar'

# Academic
# cask 'mactex-no-gui'
# cask 'papers'
# cask 'mendeley'

# Audio & Video
cask 'vlc'
cask 'imageoptim'
cask 'blackhole-16ch'
cask 'audacity'

# Applications
cask 'firefox'
cask 'notion'
cask 'whatsapp'
cask 'messenger'
