# Cask tap
tap 'caskroom/cask'
tap 'teamookla/speedtest'

# Shells
brew 'zsh'

# Tools
brew 'coreutils'
brew 'git'
brew 'pandoc'
brew 'tree'
brew 'blueutil'

# Development
brew 'rbenv'
brew 'pyenv'
brew 'ruby-build'
cask 'visual-studio-code'

# Work + Sync
cask 'slack'
cask 'microsoft-outlook' # needed until new version is out
cask 'zoomus'
cask 'google-backup-and-sync'
cask 'google-drive-file-stream'

# Menubar
cask 'mac2imgur'
cask '1password'
cask 'itsycal'
cask 'tiles'
cask 'displaperture'
cask 'hiddenbar'
cask 'xbar'

# Academic
# cask 'mactex-no-gui'
# cask 'papers'
# cask 'mendeley'

# Audio & Video
cask 'vlc'
cask 'imageoptim'
cask 'blackhole-16ch'
cask 'audacity'

# Applications
cask 'firefox'
cask 'omnidisksweeper'
