# Cask tap
tap 'caskroom/cask'

# Shells
brew 'zsh'

# Tools
brew 'coreutils'
brew 'git'
brew 'pandoc'
brew 'tree'

# Development
brew 'rbenv'
brew 'pyenv'
brew 'ruby-build'

# Software
cask 'google-backup-and-sync'
cask 'macdown'
cask 'slack'
cask 'vlc'
cask 'mac2imgur'
cask 'papers'
cask 'google-chrome'
cask 'firefox'
cask 'visual-studio-code'
cask 'sketch'
cask 'fluid'
cask 'omnidisksweeper'
cask 'texpad'
cask 'slack'
cask '1password'